apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: alertmanager-pvc
  namespace: prometheus
spec:
# storageClassName: nfs
  accessModes:
    - ReadWriteOnce
#   - ReadWriteMany
  resources:
    requests:
      storage: 100Gi