apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: prometheus
  labels:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/component: alertmanager
data:
  alertmanager.yml: |
    global:
      resolve_timeout: 5m
      #slack_api_url: '<slack_webhook_url>'
    receivers:
    - name: default-receiver
    #- name: email_config
    #  email_configs:
    #  - to: '<to_address>'
    #    from: '<from_address>'
    #    smarthost: '<smtp_host:port>'
    #    auth_username: '<smtp_username>'
    #    auth_password: '<smtp_password>'
  
    #- name: slack-notifications
    #  slack_configs:
    #  - channel: '#alerts'

    #- name: webhook
    #  webhook_configs:
    #  - url: '<webhook_url>'  
    
    route:
      group_by:
      - job
      group_interval: 5m
      group_wait: 10s
      receiver: default-receiver
    # receiver: email_config
    # receiver: slack-notifications
    # receiver: webhook
      repeat_interval: 30m