apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-ini
  namespace: ${NAMESPACE}
  labels:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/component: grafana
data:
  grafana.ini: |
    [analytics]
    check_for_updates = true
    [grafana_net]
    url = https://grafana.net
    [log]
    mode = console
    [paths]
    data = /var/lib/grafana/data
    logs = /var/log/grafana
    plugins = /var/lib/grafana/plugins