apiVersion: v1
kind: ServiceAccount
metadata:
  name: alertmanager
  namespace: prometheus
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: alertmanager
  namespace: prometheus
  labels: &Labels
    k8s-app: alertmanager
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/component: alertmanager
spec:
  serviceName: alertmanager-operated
  replicas: 2
  podManagementPolicy: OrderedReady
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels: *Labels
  template:
    metadata:
      labels: *Labels
    spec:
      serviceAccountName: alertmanager
      containers:
        - name: alertmanager
          image: srinisbook/alertmanager:v1.0
          imagePullPolicy: Always
          args:
            - --config.file=/etc/config/alertmanager.yml
            - --storage.path=/alertmanager
            - --web.listen-address=:9093
            - --web.route-prefix=/
            - --mesh.listen-address=$(POD_IP):6783
            - --mesh.peer=alertmanager-0.alertmanager-operated.=$(NAMESPACE).svc:6783
            - --mesh.peer=alertmanager-1.alertmanager-operated.=$(NAMESPACE).svc:6783
            - --log.level=debug
          env:
          - name: POD_IP
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: status.podIP
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
          ports:
            - containerPort: 9093
              name: http
            - containerPort: 6783
              name: mesh
          readinessProbe:
            httpGet:
              path: /#/status
              port: 9093
            initialDelaySeconds: 30
            timeoutSeconds: 30
          volumeMounts:
            - name: config-volume
              mountPath: /etc/config
            - name: alertmanager-data
              mountPath: "/alertmanager"
              subPath: ""
          resources: {}
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: k8s-app
                operator: In
                values:
                - alertmanager
            topologyKey: "kubernetes.io/hostname"
      volumes:
        - name: config-volume
          configMap:
            name: alertmanager-config
        - name: alertmanager-data
          persistentVolumeClaim:
            claimName: alertmanager-pvc
      